### ISSUE TITLE
images

### ISSUE THREAD

**Issue by jaybdub** [NVIDIA-AI-IOT/jetracer#1]
![all_laid_out_02](https://user-images.githubusercontent.com/4212806/60303370-1810c700-98eb-11e9-9393-dfc3e8799453.jpg)

**Comment by tokk-nv** [comment]
![IMG_7726](https://user-images.githubusercontent.com/25759564/60384726-40f1a300-9a36-11e9-90df-e8fdcf2f69ae.jpg)
