### ISSUE TITLE
How to reverse camera outupt?

### ISSUE THREAD

**Issue by haroonhublikar12** [NVIDIA-AI-IOT/jetracer#115]
I am using imx219 160° camera on my jetracer. I have attached it upside down like everyone else. How can i reverse the camera output? I am getting reversed output in interactive regression.

**Comment by krissdap** [comment]
I think the simplest way you can do it is to modify the Jetcam's CSI_Camera 
https://github.com/NVIDIA-AI-IOT/jetcam/blob/master/jetcam/csi_camera.py
(do it in your local code)

After each line of
<code>
re, image = self.cap.read()
</code>

you add a line of 
<code>
image = cv2.rotate(image, cv2.ROTATE_180)
</code>

which would replace each captured frame with a rotated one.
