### ISSUE TITLE
How to stop jetracer

### ISSUE THREAD

**Issue by yahya200** [NVIDIA-AI-IOT/jetracer#120]
How can I stop jetracer when it is outside the road or with untrained images
where should I put (car.throttle = -0.00 car.steering = -0.00)  in the road following code?

**Comment by crother94** [comment]
You can always just switch CH3 on the transmitter so that it's controlled manually instead of by the GPU. It's quite a bit faster than setting throttle to 0 in the notebook.

**Comment by yahya200** [comment]
Thank you for your reply
