### ISSUE TITLE
Tamiya TT-02 Jetracer isn't moving, issue seems to be the multiplexer

### ISSUE THREAD

**Issue by ParkerAI** [NVIDIA-AI-IOT/jetracer#132]
Got the Tamiya built and mounted, but having issues getting it moving.

I've managed to, I believe, isolate the problem to the multiplexer. When routed through there none of the notebooks will execute. Plugging into the PG directly allows for both movement and rotation, so that seems to be the a pretty clear indication of the fault.

Issue is, I'm not familiar enough with the hardware to simply conclude the multiplexer is bad, or if this is something I can resolve myself. Are there any methods of diagnosis I can use to see if the multiplexer is simply bad or if the issue is somewhere in my build?

**Comment by gitnabeshin** [comment]
Hi, I build my jetracer like this fig. without the multiplexer.

https://qiita.com/Nabeshin/items/99ddcdf8e6a4038e5844#車体の組み立て

The multiplexer is just a switcher between 2 signals of RC and Jetson Nano.
This makes jetracer simply and safely work with Jetson Nano and just for steering controlled by ML.
(You must control jetracer forward and backward with RC)

I hope you can make it clear your multiplexer is bad or not.

**Comment by ParkerAI** [comment]
Managed to get it figured out and it's moving now, thank you for the response. Turns out I just forgot to flip the override out of manual like an idiot.

**Comment by coltonwestern** [comment]
Hi @ParkerAI could you clarify what it means to "flip the override out of manual"? I came across that while running the first basic motion notebook and am having trouble figuring that out.

**Comment by CHPA6244** [comment]
I'm sorry, it's been quite a while and I do not remember exactly what I did. I'll try and remember tomorrow, but the only thing I can recall here was that it was a switch on the radio controller that toggled control between it and the code. It's been so long I can't swear to that being the solution however. I do recall that it was a silly, simple solution, nothing to do with my wiring or system.
