### ISSUE TITLE
torch2trt  no attribute for reciprocal_

### ISSUE THREAD

**Issue by nelsonjin** [NVIDIA-AI-IOT/jetracer#27]
ERROR : AttributeError: module 'torch' has no attribute 'reciprocal_'

while running 
'''
from torch2trt import torch2trt
data = torch.zeros((1, 3, 224, 224)).cuda().half()
model_trt = torch2trt(model, [data], fp16_mode=True)
'''

is there any version problem for torch2trt? 

![image](https://user-images.githubusercontent.com/5908118/66669557-61aed300-ec8a-11e9-9e66-e06054ba9302.png)

**Comment by jaybdub** [comment]
Hi nelsonjin,

Which version of PyTorch is this using?  I believe using version 1.2 would resolve this issue.

That said, this error seems like an issue in torch2trt that should be addressed.  I will look into this.

Please let me know if you have any additional questions.

Best,
John

**Comment by nelsonjin** [comment]
torch is preinstalled by "jetcard_v0p0p0.zip", which is installed by jetcard.  version : 1.1.0a0+b457266


`wget https://nvidia.box.com/shared/static/veo87trfaawj5pfwuqvhl6mzc5b55fbj.whl -O torch-1.1.0a0+b457266-cp36-cp36m-linux_aarch64.whl
echo $password | sudo -S pip3 install -U numpy torch-1.1.0a0+b457266-cp36-cp36m-linux_aarch64.whl`

**Comment by nelsonjin** [comment]
Solved by installing torch-1.2.0

**Comment by ilhmfahmi** [comment]
how to installing torch 1.2.0?

**Comment by ilhmfahmi** [comment]
> Solved by installing torch-1.2.0

How to install torch-1.2.0?
