### ISSUE TITLE
images

### ISSUE THREAD

**Issue by chitoku** [NVIDIA-AI-IOT/jetracer#30]
![Latrax-Rally_in_box](https://user-images.githubusercontent.com/262161/67135572-ff952700-f1cf-11e9-9676-860464505818.png)
![Latrax-Rally_without_shell](https://user-images.githubusercontent.com/262161/67135575-0328ae00-f1d0-11e9-99d7-a39cf997d9da.png)
![Tamiya-TT02-Subaru_in_box](https://user-images.githubusercontent.com/262161/67135640-9b269780-f1d0-11e9-87b7-09faacfa81cc.jpg)
![Tamiya-TT02_without_shell](https://user-images.githubusercontent.com/262161/67135642-9c57c480-f1d0-11e9-9424-a780f559d546.jpg)

**Comment by tokk-nv** [comment]
![JetRacer_Latrax-Rally](https://user-images.githubusercontent.com/25759564/67249602-1ed4c400-f41d-11e9-8373-fe07b352c711.jpg)
![JetRacer_Tamiya-TT02](https://user-images.githubusercontent.com/25759564/67249604-1ed4c400-f41d-11e9-8774-8249575f39ac.jpg)

**Comment by tokk-nv** [comment]
![JetRacer_Latrax-Rally_w](https://user-images.githubusercontent.com/25759564/67250038-b1c22e00-f41e-11e9-82d2-bbb17526310b.jpg)
![JetRacer_Tamiya-TT02_w](https://user-images.githubusercontent.com/25759564/67250039-b1c22e00-f41e-11e9-931f-98c1729550d0.jpg)

**Comment by jaybdub** [comment]
![jetracer](https://user-images.githubusercontent.com/4212806/67442844-3e075900-f5b7-11e9-9d73-c9d4cb9a5021.gif)

**Comment by jaybdub** [comment]
![jetracer](https://user-images.githubusercontent.com/4212806/67442981-ce459e00-f5b7-11e9-9c8a-14ab360decb8.gif)
