### ISSUE TITLE
STL files dimension unit

### ISSUE THREAD

**Issue by AlbanoL** [NVIDIA-AI-IOT/jetracer#33]
Hi,
I am thinking to order an online 3D print service to purchase the supports and the provider asks if the unit dimensions are in millimeters, centimeters or inches?

Does anyone suggest any 3d printing services?

Thanks,
Albano

**Comment by chitoku** [comment]
Hi AlbanoL,
They are supposed to be in millimeters, but please check the final dimension just in case.
