### ISSUE TITLE
error message after running Jetracer code

### ISSUE THREAD

**Issue by goodeyedeer** [NVIDIA-AI-IOT/jetracer#34]
show error message as below, please kindly help

[![KHwbbd.md.jpg](https://s2.ax1x.com/2019/11/01/KHwbbd.md.jpg)](https://imgchr.com/i/KHwbbd)

**Comment by jaybdub** [comment]
Hi goodeyedeer,

Thanks for reaching out, and sorry for the delayed response.  This should be resolved by updating the version of PyTorch to use version 1.2.

You can find it here

https://devtalk.nvidia.com/default/topic/1049071/jetson-nano/pytorch-for-jetson-nano-version-1-3-0-now-available/

Best,
John

**Comment by TimIWT** [comment]
> Hi goodeyedeer,
> 
> Thanks for reaching out, and sorry for the delayed response. This should be resolved by updating the version of PyTorch to use version 1.2.
> 
> You can find it here
> 
> https://devtalk.nvidia.com/default/topic/1049071/jetson-nano/pytorch-for-jetson-nano-version-1-3-0-now-available/
> 
> Best,
> John

Hi John.

I installed the new PyTorch version, but afterwards i cant install ResNet, because the Download stops at around 80% for some reason. Is this issue known?

Best regards,
Tim
