### ISSUE TITLE
import jetracer error

### ISSUE THREAD

**Issue by tanakataiki4** [NVIDIA-AI-IOT/jetracer#35]
I setup python using sudo python3 setup.py install
The result I think is OK but I ran basic_motion.ipynb script copying to basic_motion.py
And run the script but raise RuntimeError("The current user does not have permissions set to "....

Does anyone have any idea how to solve this?

OS : linux18.04
python 3.6.8
jetsonnano local

----------------Output of setup.py-------------------

running install
running bdist_egg
running egg_info
writing jetracer.egg-info/PKG-INFO
writing dependency_links to jetracer.egg-info/dependency_links.txt
writing requirements to jetracer.egg-info/requires.txt
writing top-level names to jetracer.egg-info/top_level.txt
reading manifest file 'jetracer.egg-info/SOURCES.txt'
writing manifest file 'jetracer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
creating build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/jetracer
copying build/lib/jetracer/racecar.py -> build/bdist.linux-aarch64/egg/jetracer
copying build/lib/jetracer/nvidia_racecar.py -> build/bdist.linux-aarch64/egg/jetracer
copying build/lib/jetracer/__init__.py -> build/bdist.linux-aarch64/egg/jetracer
byte-compiling build/bdist.linux-aarch64/egg/jetracer/racecar.py to racecar.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/jetracer/nvidia_racecar.py to nvidia_racecar.cpython-36.pyc
byte-compiling build/bdist.linux-aarch64/egg/jetracer/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying jetracer.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying jetracer.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying jetracer.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying jetracer.egg-info/requires.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying jetracer.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/jetracer-0.0.0-py3.6.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing jetracer-0.0.0-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/jetracer-0.0.0-py3.6.egg
Copying jetracer-0.0.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
jetracer 0.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/jetracer-0.0.0-py3.6.egg
Processing dependencies for jetracer==0.0.0
Searching for adafruit-circuitpython-servokit==1.1.0
Best match: adafruit-circuitpython-servokit 1.1.0
Processing adafruit_circuitpython_servokit-1.1.0-py3.6.egg
adafruit-circuitpython-servokit 1.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/adafruit_circuitpython_servokit-1.1.0-py3.6.egg
Searching for adafruit-circuitpython-register==1.7.1
Best match: adafruit-circuitpython-register 1.7.1
Processing adafruit_circuitpython_register-1.7.1-py3.6.egg
adafruit-circuitpython-register 1.7.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/adafruit_circuitpython_register-1.7.1-py3.6.egg
Searching for adafruit-circuitpython-pca9685==3.2.5
Best match: adafruit-circuitpython-pca9685 3.2.5
Processing adafruit_circuitpython_pca9685-3.2.5-py3.6.egg
adafruit-circuitpython-pca9685 3.2.5 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/adafruit_circuitpython_pca9685-3.2.5-py3.6.egg
Searching for adafruit-circuitpython-motor==2.0.0
Best match: adafruit-circuitpython-motor 2.0.0
Processing adafruit_circuitpython_motor-2.0.0-py3.6.egg
adafruit-circuitpython-motor 2.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/adafruit_circuitpython_motor-2.0.0-py3.6.egg
Searching for adafruit-circuitpython-busdevice==4.0.0
Best match: adafruit-circuitpython-busdevice 4.0.0
Processing adafruit_circuitpython_busdevice-4.0.0-py3.6.egg
adafruit-circuitpython-busdevice 4.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/adafruit_circuitpython_busdevice-4.0.0-py3.6.egg
Searching for Adafruit-Blinka==2.5.0
Best match: Adafruit-Blinka 2.5.0
Processing Adafruit_Blinka-2.5.0-py3.6.egg
Adafruit-Blinka 2.5.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/Adafruit_Blinka-2.5.0-py3.6.egg
Searching for spidev==3.4
Best match: spidev 3.4
Processing spidev-3.4-py3.6-linux-aarch64.egg
spidev 3.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/spidev-3.4-py3.6-linux-aarch64.egg
Searching for sysv-ipc==1.0.0
Best match: sysv-ipc 1.0.0
Processing sysv_ipc-1.0.0-py3.6-linux-aarch64.egg
sysv-ipc 1.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/sysv_ipc-1.0.0-py3.6-linux-aarch64.egg
Searching for Jetson.GPIO==2.0.1
Best match: Jetson.GPIO 2.0.1
Adding Jetson.GPIO 2.0.1 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for Adafruit-PureIO==0.2.3
Best match: Adafruit-PureIO 0.2.3
Processing Adafruit_PureIO-0.2.3-py3.6.egg
Adafruit-PureIO 0.2.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/Adafruit_PureIO-0.2.3-py3.6.egg
Searching for Adafruit-PlatformDetect==1.3.4
Best match: Adafruit-PlatformDetect 1.3.4
Processing Adafruit_PlatformDetect-1.3.4-py3.6.egg
Adafruit-PlatformDetect 1.3.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.6/dist-packages/Adafruit_PlatformDetect-1.3.4-py3.6.egg
Finished processing dependencies for jetracer==0.0.0

-----------------------------------------RunTime Error is below--------------------------------

Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    from jetracer.nvidia_racecar import NvidiaRacecar
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/jetracer-0.0.0-py3.6.egg/jetracer/nvidia_racecar.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/adafruit_circuitpython_servokit-1.1.0-py3.6.egg/adafruit_servokit.py", line 52, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Adafruit_Blinka-2.5.0-py3.6.egg/board.py", line 86, in <module>
    from adafruit_blinka.board.jetson_nano import *
  File "/usr/local/lib/python3.6/dist-packages/Adafruit_Blinka-2.5.0-py3.6.egg/adafruit_blinka/board/jetson_nano.py", line 3, in <module>
    from adafruit_blinka.microcontroller.tegra.t210 import pin
  File "/usr/local/lib/python3.6/dist-packages/Adafruit_Blinka-2.5.0-py3.6.egg/adafruit_blinka/microcontroller/tegra/t210/pin.py", line 3, in <module>
    import Jetson.GPIO as GPIO
  File "/usr/local/lib/python3.6/dist-packages/Jetson/GPIO/__init__.py", line 1, in <module>
    from .gpio import *
  File "/usr/local/lib/python3.6/dist-packages/Jetson/GPIO/gpio.py", line 33, in <module>
    raise RuntimeError("The current user does not have permissions set to "
RuntimeError: The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this

**Comment by Xiangjun-Gao** [comment]
Have you solved it?
I meet this problem too.
How can I solve it.
