### ISSUE TITLE
Issue running basic_motion.ipynb directly after software setup

### ISSUE THREAD

**Issue by ctye85** [NVIDIA-AI-IOT/jetracer#42]
![Screen Shot 2019-12-26 at 17 19 21 (2)](https://user-images.githubusercontent.com/56577172/71523136-f8467400-290a-11ea-8a1d-2383009786e6.png)
![Screen Shot 2019-12-26 at 17 19 30 (2)](https://user-images.githubusercontent.com/56577172/71523137-f8df0a80-290a-11ea-88e5-8afe724c13e9.png)

Forgive my ignorance, as I'm sure the answer to this issue is incredibly simple.

I have attempted to run basic_motion.ipynb after finishing the software setup. However, there are apparently some erroneous values in the code, and I am not experienced enough to figure out what to do to fix it.

I figured posting this as an issue would help others who get stuck right after the software setup as well.

Thanks for any advice you can give, and happy holidays!

**Comment by Ziegan** [comment]
Recently,

I made another tamiya build using the list of materials shared in this page..,

While executing the program (basic_motion), right after the software setup
i got this error.


Any suggestions to overcome this error

![Error1](https://user-images.githubusercontent.com/45599183/71541919-b55ebd80-2957-11ea-9fea-889148f4ac73.png)
![Error2](https://user-images.githubusercontent.com/45599183/71541921-be4f8f00-2957-11ea-97b5-d677710d0237.png)
![Error3](https://user-images.githubusercontent.com/45599183/71541924-c7406080-2957-11ea-96a1-dfeeb1c9c4ac.png)



Thanks

**Comment by krissdap** [comment]
I had this problem.
Fixed it by running this command once on a terminal, then restart the notebook.

<code>
sudo pip3 install Adafruit-PureIO --upgrade
</code>
It'll upgrade Adafruit-PureIO package to 1.0.4 from 0.2.3 which resolve this problem.

credit to tsteinle at https://devtalk.nvidia.com/default/topic/1068733/jet-racer-basic-motion-error/?offset=2

**Comment by ctye85** [comment]
Thanks for the suggestion krissdap, I'll give it a shot when I can and report back!

**Comment by ctye85** [comment]
Coworker tried that out on our car at work and it fixed everything. Thanks again for the advice!

**Comment by krissdap** [comment]
Glad it helps!
Thanks for reporting back.
