### ISSUE TITLE
Issue compiling basic_motion.ipynb

### ISSUE THREAD

**Issue by risingwisdom** [NVIDIA-AI-IOT/jetracer#46]
After following all the software setup, when I try to run the first line in basic_motion.ipynb, I get this error:
![issue1](https://user-images.githubusercontent.com/15527186/72196415-c504ea00-33cc-11ea-88bd-6a82b3bb21c1.PNG)

![issue](https://user-images.githubusercontent.com/15527186/72196362-60498f80-33cc-11ea-9738-68bc713a1615.PNG)

saying an integer was required but got a type bytearray.

Not sure what to do to fix it.

**Comment by ctye85** [comment]
https://github.com/NVIDIA-AI-IOT/jetracer/issues/42

I asked this a little while ago, and got some help. You just have to upgrade Adafruit-PureIO package from 1.0.4 to 0.2.3. This command in the terminal should do it:

sudo pip3 install Adafruit-PureIO --upgrade

**Comment by risingwisdom** [comment]
That made it work! Thanks.
