### ISSUE TITLE
wiki page links

### ISSUE THREAD

**Issue by xxzvxx** [NVIDIA-AI-IOT/jetracer#5]
on the wiki page none of the link are working... :(

Follow these steps and you should be up and running with JetRacer in no time!

Get parts from the bill of materials
Follow the hardware setup
Follow the software setup
Run through the examples

**Comment by jaybdub** [comment]
Hi xxzvxx, 

Thanks for pointing this out.  We’ve actually migrated the documentation into the repository itself for this project.  Sorry, please follow the links in the README.

Best,
John
