### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by Ziegan** [NVIDIA-AI-IOT/jetracer#50]
Can anyone share the successful training method or a training video !

1) I have tried a lot but the car doesn't turn through the curves and if i adjust it to make curve...even for fractional adjustments in the value makes the car to be turning forever.

2) I had also tried various positions of camera from the default position(where the feed image has half road and half of the room) to fully focusing the road by tilting the camera downwards a little.

**Comment by kyung-il-Jang** [comment]
Did you solve it?
I'm still failing on road following.
I took a lot of pictures and trained a lot, but I don't know why.
Is it working well now?
