### ISSUE TITLE
BLE comm.  between JetRacer and Phone App

### ISSUE THREAD

**Issue by Sunggu-Kim** [NVIDIA-AI-IOT/jetracer#53]
Hi, This is SG Kim,

I hope to send some data from Phone App to JetRacer based on BLE comm.
Can you guide what to do to enable BLE comm between JetRacer and Phone App based on Python?
( JetRacer : device ( Peripheral ), Phone  : Central )

I tried to install pybluez, but failed it.  

Thanks in advance for your help.

**Comment by kyung-il-Jang** [comment]
May I ask you a bit about jetracer road_following?

**Comment by Sunggu-Kim** [comment]
> May I ask you a bit about jetracer road_following?
Hi, KI Jang, Sorry... I saw this today.
What's it if you have still it?

**Comment by kyung-il-Jang** [comment]
Hi, thanks for answering.
Did the road following work well with the default code?
My car continues driving to the right.
So, I change the bias value, but it continues.
Are there any precautions?

**Comment by Sunggu-Kim** [comment]
Ahh... I also saw the same thing.
But, I didn't try to do any tunning.
I am focusing on other my own function.

Sorry...

SG Kim
