### ISSUE TITLE
jetracer - road following problem

### ISSUE THREAD

**Issue by kyung-il-Jang** [NVIDIA-AI-IOT/jetracer#54]
I definitely took 400 pictures and 10 trainings, but in road_following the jetracer can't follow the line properly. Obviously the blue dot in the 'evaluate' followed the line well, but in the road_following the jetracer doesn't have it properly.

**Comment by itsklee** [comment]
Check the alignment of the vehicle. 
basic_motion ( straight and steer gain )

**Comment by joker-wutong** [comment]
Is it solved? I have the same problem
