### ISSUE TITLE
No Display with JetRacer Image

### ISSUE THREAD

**Issue by bjkayani** [NVIDIA-AI-IOT/jetracer#55]
When i etched the image on the sd card and booted up my jetson nano, i got no display. No idea where to go from here. Any help would be appreciated.

**Comment by tokk-nv** [comment]
Hi,
If you have the B01 revision of Jetson Nano Developer Kit (that has two camera connectors), you need an SD card image that is based on JetPack 4.3 which support B01.
Please check the discussion on issue #57 and my comment in the thread.
https://github.com/NVIDIA-AI-IOT/jetracer/issues/57

Chitoku
