### ISSUE TITLE
Run the project of  Jetbot on this

### ISSUE THREAD

**Issue by lilyswang** [NVIDIA-AI-IOT/jetracer#58]
Can we run the project of jetbot on this, for example: follow something/people, avoid obstacles, etc

**Comment by openbsod** [comment]
Hi.

General answer - yes you can, with a a lot of 'if' and 'cons'. Jetracer natively drives much faster compared with jetbot and you will hit very poor perfomance without tuning of everything. Jetbot initially not so great perfomant and jetracer`s motors speed just highlites this factor, iws.

BR, Ed.
