### ISSUE TITLE
Can not trainning ?  It always block when training

### ISSUE THREAD

**Issue by tjyuanxi** [NVIDIA-AI-IOT/jetracer#63]
Hi,
     I have take >200 images ,but only twice circles。
    Then I clicked train , 1 epochs or 8 epochs or 10 epochs . I cannot complete progress, it always blocked. Like  the picture below.

![image](https://user-images.githubusercontent.com/34560457/81811615-7ec8be80-9557-11ea-826c-d787f682561b.png)
     help me!

**Comment by tjyuanxi** [comment]
I set it to 10W mode, it blocked too.
I see meminfo : 3.3G/4G

**Comment by jasonlililililili** [comment]
I have encountered the same problem and turns out that there is an image that corrupted (size = 0) and that stucks the training progress from running. You may want to check out the size of each image to see if there are any abnormality.
