### ISSUE TITLE
Mini PC payload

### ISSUE THREAD

**Issue by antoan** [NVIDIA-AI-IOT/jetracer#7]
Would it be too heavy on the chassis to add an Intel NUC to jetracer?

**Comment by tokk-nv** [comment]
Hi antoan,
JetRacer does not necessarily need to be implemented on 1/18 scale Latrax Rally car chassis, it can use much bigger car chassis as well.
You probably would be able to find other projects that demonstrate how to put an Intel NUC on 1/10 or even bigger form factor RC car chassis.
