### ISSUE TITLE
Interactive Regression Help

### ISSUE THREAD

**Issue by msvauken** [NVIDIA-AI-IOT/jetracer#79]
Hi, 
I am trying to train the vehicle with following these steps... live button, train button, then click on left image.  When I click on the left image, am I supposed to click on one area then start over with a new image?  what am I clicking on exactly?  items to avoid? a line in a track?

Also, when I am done with the image and move the car forward, the image does not reset to the next view where the car is at in the left image.  I thought this image would change after the car moves forward.  Attached is the 3 images I see on the screen.   Not really sure I am doing this correctly.  Is there anyone that can provide some quick step-by-step instructions on how to get started with recording images?  Thanks.

![Capture](https://user-images.githubusercontent.com/71997075/95039071-a3e3d800-0684-11eb-8b16-c383047ff46b.PNG)

**Comment by diamondbarcode** [comment]
from my experience after train and you still not see your green circle in evaluation it mean you train in low epochs ( need increase count ) or not enough data to work with ( take more picture ).

I think you need some line or color indicator for it to work with. I think wood on wood like your picture would be hard for computer to figure out.
