### ISSUE TITLE
No HDMI output

### ISSUE THREAD

**Issue by sudo-michael** [NVIDIA-AI-IOT/jetracer#81]
I'm able to ssh to the jetson just fine, but I can't get any type of desktop environment to display when I use a HDMI cable. I tried using the following https://developer.nvidia.com/jetson-nano-sd-card-image and am able to get HDMI output to work just fine, but whenever I try to use the one provided in the software setup https://drive.google.com/open?id=1wXD1CwtxiH5Mz4uSmIZ76fd78zDQltW_ it doesn't seam to work.

**Comment by jreinmuth** [comment]
Hi, 
you can check with xrandr if hdmi is enabled. If not, you can try to set HDMI to HD 720p 

xrandr --addmode HDMI-1-1 1280x720
xrandr --output HDMI-1-1 --mode 1280x720

if this will work, you can increase values for resolution as well
