### ISSUE TITLE
Tracking and obstacle avoidance of jetracer

### ISSUE THREAD

**Issue by joker-wutong** [NVIDIA-AI-IOT/jetracer#82]
I have used jetracer smart car to achieve tracing and obstacle avoidance, but they all have a single function. Now I want to achieve obstacle avoidance while tracing. I don’t know if you have done it. Thanks for the advice

**Comment by diamondbarcode** [comment]
There is a lot of people talking about this. In Jetbot there is obstacle avoidance but not in Jetracer. If you search for issues u see them so far no one has started to work on this part of modules yet.

I was testing 2 cameras on jetson nano 1 use for road following and 1 use for show road so far it appears to me that jetson nano could not handle 2 live streams at high speed. If jetson Xavier may be able to handle the processing power need( i could be wrong).
