### ISSUE TITLE
Add support for Nvidia LaneNet DNN?

### ISSUE THREAD

**Issue by zlite** [NVIDIA-AI-IOT/jetracer#9]
We've been using LaneNet on similar small cars and it's amazing. Have you considered adding that as a pre-trained lane-follower in JetRacer?

https://twitter.com/nvidiadrive/status/1149051960940814341
https://arxiv.org/abs/1802.05591

We used this version:
https://github.com/MaybeShewill-CV/lanenet-lane-detection

**Comment by tokk-nv** [comment]
Hi Chris,
Thank you for letting us know about the LaneNet.
We will look into it.

**Comment by ArtlyStyles** [comment]
@zlite, could you please let me know which hardware platform you are running LaneNet? Based on some of the feedback for the version you are using, the network was very slow on Tx2.
