### ISSUE TITLE
module 'torch' has no attribute for reciprocal_

### ISSUE THREAD

**Issue by ilhmfahmi** [NVIDIA-AI-IOT/jetracer#90]
i have some error when trying road folowing example on jetracer 
in https://github.com/NVIDIA-AI-IOT/jetracer/issues/27 said that version 1.2 would resolve this issue
so how to upgrade torch-1.2.0? 
please help, thanks.
![reciprocal](https://user-images.githubusercontent.com/77530445/105850984-09cde400-6015-11eb-9c29-1733fd7db911.png)

**Comment by vincentandreas** [comment]
Hi @ilhmfahmi . I think you should try to install torch library from this link https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-7-0-now-available/72048

**Comment by abritten** [comment]
@ilhmfahmi I tried this and it worked earlier this month:

wget https://nvidia.box.com/shared/static/06vlvedmqpqstu1dym49fo7aapgfyyu9.whl -O torch-1.2.0a0+8554416-cp36-cp36m-linux_aarch64.whl

pip3 install numpy torch-1.2.0a0+8554416-cp36-cp36m-linux_aarch64.whl --user

But now its not working. Try it anyways.
